services:
  - type: web
    name: my-backend-service
    env: python
    plan: free
    buildCommand: ""
    startCommand: python app.py

    build:
      - apt-get update && apt-get install -y gcc python3-dev
